version: "3.8"

services:
  news-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - JASYPT_ENCRYPTOR_PASSWORD=1234567890123456
    volumes:
      - ./application.yml:/app/config/application.yml:ro
    restart: always